const experienceItems = [
  {
    year: 2019,
    date: 'experience.be.date',
    company: 'experience.be.company',
    position: 'experience.be.position',
    description: 'experience.be.description',
    link: 'https://www.ua.be-tse.com/',
    tags: ['angular'],
  },
  {
    year: 2016,
    date: 'experience.jbook.date',
    company: 'experience.jbook.company',
    position: 'experience.jbook.position',
    description: 'experience.jbook.description',
    tags: ['angular', 'apis', 'database', 'devops'],
  },
  // {
  //   year: 2020,
  //   date: 'experience.kawunu.date',
  //   company: 'experience.kawunu.company',
  //   position: 'experience.kawunu.position',
  //   description: 'experience.kawunu.description',
  //   link: 'https://www.kawunu.com',
  //   tags: ['angular', 'react', 'apis', 'database'],
  // },
  {
    year: 2021,
    date: 'experience.livee.date',
    company: 'experience.livee.company',
    position: 'experience.livee.position',
    description: 'experience.livee.description',
    link: 'https://www.livee.com/',
    tags: ['react', 'angular', 'apis', 'database', 'devops'],
  },
];

const educationItems = [
  {
    id: 1,
    name: 'Cursor AI: Learn by Building Full-Stack Next.js 15 App',
    year: 2025,
    tag: 'react',
    link: 'https://www.udemy.com/course/cursorai-nextjs/',
  },
  {
    id: 2,
    name: 'Advanced React: Design Patterns and Performance',
    year: 2025,
    tag: 'react',
    link: 'https://www.udemy.com/course/advanced-react',
  },
  {
    id: 3,
    name: 'React Hook Form: The Complete Guide with react',
    year: 2025,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-hook-form-the-complete-guide-with-react-js',
  },
  {
    id: 4,
    name: 'React Native: Advanced Concepts',
    year: 2024,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-native-advanced',
  },
  {
    id: 5,
    name: 'Modern React with Redux',
    year: 2024,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-redux',
  },
  {
    id: 6,
    name: "NestJS: The Complete Developer's Guide",
    year: 2024,
    tag: 'apis',
    link: 'https://www.udemy.com/course/nestjs-the-complete-developers-guide',
  },
  {
    id: 7,
    name: 'React Native - The Practical Guide',
    year: 2023,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-native-the-practical-guide',
  },
  {
    id: 9,
    name: "SQL and PostgreSQL: The Complete Developer's Guide",
    year: 2023,
    tag: 'database',
    link: 'https://www.udemy.com/course/sql-and-postgresql',
  },
  {
    id: 10,
    name: 'GitHub Actions - The Complete Guide',
    year: 2023,
    tag: 'devops',
    link: 'https://www.udemy.com/course/github-actions-the-complete-guide',
  },
  {
    id: 11,
    name: "Microfrontends with React: A Complete Developer's Guide",
    year: 2022,
    tag: 'react',
    link: 'https://www.udemy.com/course/microfrontend-course',
  },
  {
    id: 19,
    name: 'Secure Your ReactJs Applications With Auth0',
    year: 2022,
    tag: 'react',
    link: 'https://www.udemy.com/course/secure-your-reactjs-applications-with-auth0/',
  },
  {
    id: 12,
    name: 'Node JS: Advanced Concepts',
    year: 2022,
    tag: 'apis',
    link: 'https://www.udemy.com/course/advanced-node-for-developers',
  },
  {
    id: 14,
    name: 'Docker & Kubernetes: The Practical Guide',
    year: 2021,
    tag: 'devops',
    link: 'https://www.udemy.com/course/docker-kubernetes-the-practical-guide',
  },
  {
    id: 15,
    name: 'The Nuts and Bolts of OAuth 2.0',
    year: 2021,
    tag: 'apis',
    link: 'https://www.udemy.com/course/oauth-2-simplified',
  },
  {
    id: 13,
    name: "MongoDB - The Complete Developer's Guide",
    year: 2020,
    tag: 'database',
    link: 'https://www.udemy.com/course/mongodb-the-complete-developers-guide',
  },
  {
    id: 8,
    name: 'The Complete Node.js Developer Course (3rd Edition)',
    year: 2020,
    tag: 'apis',
    link: 'https://www.udemy.com/course/the-complete-nodejs-developer-course-2',
  },
  {
    id: 16,
    name: 'Webpack 5: The Complete Guide For Beginners',
    year: 2020,
    tag: 'devops',
    link: 'https://www.udemy.com/course/webpack-from-beginner-to-advanced',
  },
  {
    id: 17,
    name: 'Progressive Web Apps (PWA) - The Complete Guide',
    year: 2021,
    tag: 'react',
    link: 'https://www.udemy.com/course/progressive-web-app-pwa-the-complete-guide',
  },
  {
    id: 18,
    name: 'React Progressive Web App With Workbox and Webpack',
    year: 2021,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-progressive-web-app-with-workbox-and-webpack-tutorial',
  },
  {
    id: 20,
    name: 'Unit Testing for TypeScript & NodeJs Developers with Jest',
    year: 2019,
    tag: 'apis',
    link: 'https://www.udemy.com/course/unit-testing-typescript-nodejs',
  },
  {
    id: 21,
    name: 'Angular - The Complete Guide',
    year: 2019,
    tag: 'angular',
    link: 'https://www.udemy.com/course/the-complete-guide-to-angular-2',
  },
  {
    id: 22,
    name: 'Angular (Full App) with Angularfire & NgRx',
    year: 2018,
    tag: 'angular',
    link: 'https://www.udemy.com/course/angular-full-app-with-angular-material-angularfire-ngrx/',
  },
  {
    id: 23,
    name: 'Reactive Angular Course (with RxJs)',
    year: 2018,
    tag: 'angular',
    link: 'https://www.udemy.com/course/rxjs-reactive-angular-course',
  },
  {
    id: 25,
    name: 'Angular Testing Masterclass',
    year: 2018,
    tag: 'angular',
    link: 'https://www.udemy.com/course/angular-testing-course',
  },
  {
    id: 24,
    name: 'Angular Deep Dive – Beginner to Advanced',
    year: 2017,
    tag: 'angular',
    link: 'https://www.udemy.com/course/angular-course',
  },
];

const SKILLS = [
  { id: 1, name: 'React + Redux', level: 9 },
  { id: 2, name: 'React Native', level: 8 },
  { id: 3, name: 'Angular + NgRx', level: 7 },
  { id: 4, name: 'Node JS', level: 7 },
  { id: 5, name: 'MongoDB', level: 7 },
  { id: 6, name: 'Postgres', level: 6 },
  { id: 7, name: 'PHP + SQL', level: 4 },
  { id: 8, name: 'Docker + Github', level: 7 },
  { id: 9, name: 'UX/UI', level: 9 },
];

const portfolioItems = [
  {
    id: 'jbook',
    title: 'portfolio.items.jbook.title',
    tags: [
      'portfolio.tags.design',
      'portfolio.tags.layout',
      'portfolio.tags.angular',
      'portfolio.tags.express',
      'portfolio.tags.mongodb',
    ],
    image: {
      desktop: '/img/jbook-ds-1x.jpg',
      tablet: '/img/jbook-tb-1x.jpg',
      alt: 'portfolio.items.jbook.alt',
    },
    features: [
      'portfolio.items.jbook.features.feature1',
      'portfolio.items.jbook.features.feature2',
      'portfolio.items.jbook.features.feature3',
      'portfolio.items.jbook.features.feature4',
    ],
    links: {
      code: 'https://github.com/oleynichenko/book',
    },
    color: '#673bb7',
    colorLight: '#ded8e8',
  },
  {
    id: 'tests',
    title: 'portfolio.items.tests.title',
    tags: [
      'portfolio.tags.design',
      'portfolio.tags.layout',
      'portfolio.tags.express',
      'portfolio.tags.mongodb',
    ],
    image: {
      desktop: '/img/tests-ds-1x.jpg',
      tablet: '/img/tests-tb-1x.jpg',
      alt: 'portfolio.items.tests.alt',
    },
    features: [
      'portfolio.items.tests.features.feature1',
      'portfolio.items.tests.features.feature2',
      'portfolio.items.tests.features.feature3',
      'portfolio.items.tests.features.feature4',
    ],
    links: {
      code: 'https://github.com/oleynichenko/quiz-cms',
    },
    color: '#e4476c',
    colorDark: '#621527',
  },
  {
    id: 'words',
    title: 'portfolio.items.words.title',
    tags: [
      'portfolio.tags.angular',
      'portfolio.tags.ngrx',
      'portfolio.tags.angularfire2',
    ],
    image: {
      desktop: '/img/words-ds-1x.jpg',
      tablet: '/img/words-tb-1x.jpg',
      alt: 'portfolio.items.words.alt',
    },
    features: [
      'portfolio.items.words.features.feature1',
      'portfolio.items.words.features.feature2',
      'portfolio.items.words.features.feature3',
      'portfolio.items.words.features.feature4',
    ],
    links: {
      code: 'https://github.com/oleynichenko/english-words-trainer',
      demo: 'http://english-words-trainer.s3-website.eu-central-1.amazonaws.com/',
    },
    color: '#303030',
    colorLight: '#F2F2F2',
  },
  {
    id: 'time',
    title: 'portfolio.items.time.title',
    tags: ['portfolio.tags.angular', 'portfolio.tags.bootstrap'],
    image: {
      desktop: '/img/time-ds-1x.jpg',
      tablet: '/img/time-tb-1x.jpg',
      alt: 'portfolio.items.time.alt',
    },
    features: [
      'portfolio.items.time.features.feature1',
      'portfolio.items.time.features.feature2',
      'portfolio.items.time.features.feature3',
      'portfolio.items.time.features.feature4',
    ],
    links: {
      code: 'https://github.com/oleynichenko/time-tracker',
      demo: 'http://time-tracker-we1r4s.s3-website-us-east-1.amazonaws.com',
    },
    color: '#527a51',
    colorLight: '#dff6de',
  },
  {
    id: 'recipe',
    title: 'portfolio.items.recipe.title',
    tags: [
      'portfolio.tags.angular',
      'portfolio.tags.ngrx',
      'portfolio.tags.firebase',
      'portfolio.tags.bootstrap',
    ],
    image: {
      desktop: '/img/recipe-ds-1x.jpg',
      tablet: '/img/recipe-tb-1x.jpg',
      alt: 'portfolio.items.recipe.alt',
    },
    features: [
      'portfolio.items.recipe.features.feature1',
      'portfolio.items.recipe.features.feature2',
      'portfolio.items.recipe.features.feature3',
      'portfolio.items.recipe.features.feature4',
    ],
    links: {
      code: 'https://github.com/oleynichenko/recipe-book-ngrx',
      demo: 'http://recipe-book12345.s3-website.eu-central-1.amazonaws.com/',
    },
    color: '#e7e7e7',
    colorDark: '#2f2828',
  },
  {
    id: 'fitness',
    title: 'portfolio.items.fitness.title',
    tags: [
      'portfolio.tags.angular',
      'portfolio.tags.ngrx',
      'portfolio.tags.angularfire2',
    ],
    image: {
      desktop: '/img/fitness-ds-1x.jpg',
      tablet: '/img/fitness-tb-1x.jpg',
      alt: 'portfolio.items.fitness.alt',
    },
    features: [
      'portfolio.items.fitness.features.feature1',
      'portfolio.items.fitness.features.feature2',
      'portfolio.items.fitness.features.feature3',
      'portfolio.items.fitness.features.feature4',
      'portfolio.items.fitness.features.feature5',
    ],
    links: {
      code: 'https://github.com/oleynichenko/fitness-tracker-ngrx',
      demo: 'https://fitness-tracker-221a4.firebaseapp.com',
    },
    color: '#3f51b5',
    colorLight: '#e8eaf9',
  },
  {
    id: 'typing',
    title: 'portfolio.items.typing.title',
    tags: ['portfolio.tags.node', 'portfolio.tags.yargs'],
    image: {
      desktop: '/img/typing-ds-1x.jpg',
      tablet: '/img/typing-tb-1x.jpg',
      alt: 'portfolio.items.typing.alt',
    },
    features: [
      'portfolio.items.typing.features.feature1',
      'portfolio.items.typing.features.feature2',
      'portfolio.items.typing.features.feature3',
      'portfolio.items.typing.features.feature4',
      'portfolio.items.typing.features.feature5',
    ],
    links: {
      code: 'https://github.com/oleynichenko/typing-practice',
    },
    color: '#8b9a62',
    colorDark: '#2a2b25',
  },
  {
    id: 'azbyka',
    title: 'portfolio.items.azbyka.title',
    tags: ['portfolio.tags.design'],
    image: {
      desktop: '/img/azb-ds-1x.jpg',
      tablet: '/img/azb-tb-1x.jpg',
      alt: 'portfolio.items.azbyka.alt',
    },
    features: [
      'portfolio.items.azbyka.features.feature1',
      'portfolio.items.azbyka.features.feature2',
      'portfolio.items.azbyka.features.feature3',
      'portfolio.items.azbyka.features.feature4',
    ],
    links: {
      code: 'https://www.behance.net/gallery/70632601/Azbykaru-redesign',
    },
    color: '#6E4B0B',
    colorLight: '#FFF6E5',
  },
  {
    id: 'slider',
    title: 'portfolio.items.slider.title',
    tags: ['portfolio.tags.javascript', 'portfolio.tags.svg'],
    image: {
      desktop: '/img/slider-ds-1x.jpg',
      tablet: '/img/slider-tb-1x.jpg',
      alt: 'portfolio.items.slider.alt',
    },
    features: [
      'portfolio.items.slider.features.feature1',
      'portfolio.items.slider.features.feature2',
      'portfolio.items.slider.features.feature3',
      'portfolio.items.slider.features.feature4',
    ],
    links: {
      code: 'https://codepen.io/oleynichenkos/pen/BMQVgg',
    },
    color: '#ebdcff',
    colorDark: '#35303c',
  },
  {
    id: 'device',
    title: 'portfolio.items.device.title',
    tags: ['portfolio.tags.layout', 'portfolio.tags.design'],
    image: {
      desktop: '/img/device-ds-1x.jpg',
      tablet: '/img/device-tb-1x.jpg',
      alt: 'portfolio.items.device.alt',
    },
    features: [
      'portfolio.items.device.features.feature1',
      'portfolio.items.device.features.feature2',
      'portfolio.items.device.features.feature3',
      'portfolio.items.device.features.feature4',
      'portfolio.items.device.features.feature5',
    ],
    links: {
      code: 'https://github.com/oleynichenko/device',
      demo: 'https://oleynichenko.github.io/device/index.html',
    },
    color: '#ffe27f',
    colorDark: '#665A32',
  },
  {
    id: 'pixel',
    title: 'portfolio.items.pixel.title',
    tags: ['portfolio.tags.javascript'],
    image: {
      desktop: '/img/pixel-ds-1x.jpg',
      tablet: '/img/pixel-tb-1x.jpg',
      alt: 'portfolio.items.pixel.alt',
    },
    features: [
      'portfolio.items.pixel.features.feature1',
      'portfolio.items.pixel.features.feature2',
      'portfolio.items.pixel.features.feature3',
      'portfolio.items.pixel.features.feature4',
    ],
    links: {
      code: 'https://github.com/oleynichenko/pixel-hunter',
      demo: 'https://oleynichenko.github.io/pixel-hunter/',
    },
    color: '#b3cfd0',
    colorDark: '#475252',
  },
  {
    id: 'brb',
    title: 'portfolio.items.brb.title',
    tags: ['portfolio.tags.layout'],
    image: {
      desktop: '/img/brb-ds-1x.jpg',
      tablet: '/img/brb-tb-1x.jpg',
      alt: 'portfolio.items.brb.alt',
    },
    features: [
      'portfolio.items.brb.features.feature1',
      'portfolio.items.brb.features.feature2',
      'portfolio.items.brb.features.feature3',
      'portfolio.items.brb.features.feature4',
      'portfolio.items.brb.features.feature5',
    ],
    links: {
      code: 'https://github.com/oleynichenko/barbershop',
      demo: 'https://oleynichenko.github.io/barbershop/index.html',
    },
    color: '#000',
    colorLight: '#F2F2F2',
  },
  {
    id: 'pilates',
    title: 'portfolio.items.pilates.title',
    tags: [
      'portfolio.tags.design',
      'portfolio.tags.layout',
      'portfolio.tags.php',
      'portfolio.tags.javascript',
    ],
    image: {
      desktop: '/img/pilates-ds-1x.jpg',
      tablet: '/img/pilates-tb-1x.jpg',
      alt: 'portfolio.items.pilates.alt',
    },
    features: [
      'portfolio.items.pilates.features.feature1',
      'portfolio.items.pilates.features.feature2',
      'portfolio.items.pilates.features.feature3',
      'portfolio.items.pilates.features.feature4',
      'portfolio.items.pilates.features.feature5',
    ],
    links: {
      code: 'https://github.com/oleynichenko/pilates',
      demo: 'https://pilates-trainer.github.io',
    },
    color: '#c7ade9',
    colorDark: '#40374B',
  },
  {
    id: 'todo',
    title: 'portfolio.items.todo.title',
    tags: [
      'portfolio.tags.node',
      'portfolio.tags.express',
      'portfolio.tags.mongoose',
      'portfolio.tags.jsonwebtoken',
    ],
    image: {
      desktop: '/img/todo-ds-1x.jpg',
      tablet: '/img/todo-tb-1x.jpg',
      alt: 'portfolio.items.todo.alt',
    },
    features: [
      'portfolio.items.todo.features.feature1',
      'portfolio.items.todo.features.feature2',
      'portfolio.items.todo.features.feature3',
      'portfolio.items.todo.features.feature4',
      'portfolio.items.todo.features.feature5',
    ],
    links: {
      code: 'https://github.com/oleynichenko/Todo-App',
    },
    color: '#695EB8',
    colorLight: '#E6E2FF',
  },
  {
    id: 'daat',
    title: 'portfolio.items.daat.title',
    tags: [
      'portfolio.tags.react',
      'portfolio.tags.gatsby',
      'portfolio.tags.cssAnimations',
    ],
    image: {
      desktop: '/img/daat-ds-1x.jpg',
      tablet: '/img/daat-tb-1x.jpg',
      alt: 'portfolio.items.daat.alt',
    },
    features: [
      'portfolio.items.daat.features.feature1',
      'portfolio.items.daat.features.feature2',
      'portfolio.items.daat.features.feature3',
      'portfolio.items.daat.features.feature4',
    ],
    links: {
      code: 'https://github.com/oleynichenko/daat',
      demo: 'https://daat.agency',
    },
    color: '#000',
    colorLight: '#F2F2F2',
  },
];

const WEBSITE_FEATURES = [
  'portfolio.websiteFeatures.feature1',
  'portfolio.websiteFeatures.feature2',
  'portfolio.websiteFeatures.feature3',
  'portfolio.websiteFeatures.feature4',
  'portfolio.websiteFeatures.feature5',
  'portfolio.websiteFeatures.feature6',
];

const TECHNOLOGIES = [
  'portfolio.technologies.tech1',
  'portfolio.technologies.tech2',
  'portfolio.technologies.tech3',
  'portfolio.technologies.tech4',
  'portfolio.technologies.tech5',
  'portfolio.technologies.tech6',
];

const UPDATE_DATE = '2025-04-10';
const SECTION_HEIGHT = 400;

export {
  experienceItems,
  educationItems,
  SKILLS,
  UPDATE_DATE,
  SECTION_HEIGHT,
  TECHNOLOGIES,
  WEBSITE_FEATURES,
  portfolioItems,
};
