const experienceItems = [
  {
    year: 2019,
    date: 'experience.be.date',
    company: 'experience.be.company',
    position: 'experience.be.position',
    description: 'experience.be.description',
    link: 'https://www.ua.be-tse.com/',
    tags: ['angular'],
  },
  {
    year: 2016,
    date: 'experience.jbook.date',
    company: 'experience.jbook.company',
    position: 'experience.jbook.position',
    description: 'experience.jbook.description',
    tags: ['angular', 'apis', 'database', 'devops'],
  },
  // {
  //   year: 2020,
  //   date: 'experience.kawunu.date',
  //   company: 'experience.kawunu.company',
  //   position: 'experience.kawunu.position',
  //   description: 'experience.kawunu.description',
  //   link: 'https://www.kawunu.com',
  //   tags: ['angular', 'react', 'apis', 'database'],
  // },
  {
    year: 2021,
    date: 'experience.livee.date',
    company: 'experience.livee.company',
    position: 'experience.livee.position',
    description: 'experience.livee.description',
    link: 'https://www.livee.com/',
    tags: ['react', 'angular', 'apis', 'database', 'devops'],
  },
];

const educationItems = [
  {
    id: 1,
    name: 'Cursor AI: Learn by Building Full-Stack Next.js 15 App',
    year: 2025,
    tag: 'react',
    link: 'https://www.udemy.com/course/cursorai-nextjs/',
  },
  {
    id: 2,
    name: 'Advanced React: Design Patterns and Performance',
    year: 2025,
    tag: 'react',
    link: 'https://www.udemy.com/course/advanced-react',
  },
  {
    id: 3,
    name: 'React Hook Form: The Complete Guide with react',
    year: 2025,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-hook-form-the-complete-guide-with-react-js',
  },
  {
    id: 4,
    name: 'React Native: Advanced Concepts',
    year: 2024,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-native-advanced',
  },
  {
    id: 5,
    name: 'Modern React with Redux',
    year: 2024,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-redux',
  },
  {
    id: 6,
    name: "NestJS: The Complete Developer's Guide",
    year: 2024,
    tag: 'apis',
    link: 'https://www.udemy.com/course/nestjs-the-complete-developers-guide',
  },
  {
    id: 7,
    name: 'React Native - The Practical Guide',
    year: 2023,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-native-the-practical-guide',
  },
  {
    id: 9,
    name: "SQL and PostgreSQL: The Complete Developer's Guide",
    year: 2023,
    tag: 'database',
    link: 'https://www.udemy.com/course/sql-and-postgresql',
  },
  {
    id: 10,
    name: 'GitHub Actions - The Complete Guide',
    year: 2023,
    tag: 'devops',
    link: 'https://www.udemy.com/course/github-actions-the-complete-guide',
  },
  {
    id: 11,
    name: "Microfrontends with React: A Complete Developer's Guide",
    year: 2022,
    tag: 'react',
    link: 'https://www.udemy.com/course/microfrontend-course',
  },
  {
    id: 19,
    name: 'Secure Your ReactJs Applications With Auth0',
    year: 2022,
    tag: 'react',
    link: 'https://www.udemy.com/course/secure-your-reactjs-applications-with-auth0/',
  },
  {
    id: 12,
    name: 'Node JS: Advanced Concepts',
    year: 2022,
    tag: 'apis',
    link: 'https://www.udemy.com/course/advanced-node-for-developers',
  },
  {
    id: 14,
    name: 'Docker & Kubernetes: The Practical Guide',
    year: 2021,
    tag: 'devops',
    link: 'https://www.udemy.com/course/docker-kubernetes-the-practical-guide',
  },
  {
    id: 15,
    name: 'The Nuts and Bolts of OAuth 2.0',
    year: 2021,
    tag: 'apis',
    link: 'https://www.udemy.com/course/oauth-2-simplified',
  },
  {
    id: 13,
    name: "MongoDB - The Complete Developer's Guide",
    year: 2020,
    tag: 'database',
    link: 'https://www.udemy.com/course/mongodb-the-complete-developers-guide',
  },
  {
    id: 8,
    name: 'The Complete Node.js Developer Course (3rd Edition)',
    year: 2020,
    tag: 'apis',
    link: 'https://www.udemy.com/course/the-complete-nodejs-developer-course-2',
  },
  {
    id: 16,
    name: 'Webpack 5: The Complete Guide For Beginners',
    year: 2020,
    tag: 'devops',
    link: 'https://www.udemy.com/course/webpack-from-beginner-to-advanced',
  },
  {
    id: 17,
    name: 'Progressive Web Apps (PWA) - The Complete Guide',
    year: 2021,
    tag: 'react',
    link: 'https://www.udemy.com/course/progressive-web-app-pwa-the-complete-guide',
  },
  {
    id: 18,
    name: 'React Progressive Web App With Workbox and Webpack',
    year: 2021,
    tag: 'react',
    link: 'https://www.udemy.com/course/react-progressive-web-app-with-workbox-and-webpack-tutorial',
  },
  {
    id: 20,
    name: 'Unit Testing for TypeScript & NodeJs Developers with Jest',
    year: 2019,
    tag: 'apis',
    link: 'https://www.udemy.com/course/unit-testing-typescript-nodejs',
  },
  {
    id: 21,
    name: 'Angular - The Complete Guide',
    year: 2019,
    tag: 'angular',
    link: 'https://www.udemy.com/course/the-complete-guide-to-angular-2',
  },
  {
    id: 22,
    name: 'Angular (Full App) with Angularfire & NgRx',
    year: 2018,
    tag: 'angular',
    link: 'https://www.udemy.com/course/angular-full-app-with-angular-material-angularfire-ngrx/',
  },
  {
    id: 23,
    name: 'Reactive Angular Course (with RxJs)',
    year: 2018,
    tag: 'angular',
    link: 'https://www.udemy.com/course/rxjs-reactive-angular-course',
  },
  {
    id: 25,
    name: 'Angular Testing Masterclass',
    year: 2018,
    tag: 'angular',
    link: 'https://www.udemy.com/course/angular-testing-course',
  },
  {
    id: 24,
    name: 'Angular Deep Dive – Beginner to Advanced',
    year: 2017,
    tag: 'angular',
    link: 'https://www.udemy.com/course/angular-course',
  },
];

const SKILLS = [
  { id: 1, name: 'React + Redux', level: 9 },
  { id: 2, name: 'React Native', level: 8 },
  { id: 3, name: 'Angular + NgRx', level: 7 },
  { id: 4, name: 'Node JS', level: 7 },
  { id: 5, name: 'MongoDB', level: 7 },
  { id: 6, name: 'Postgres', level: 6 },
  { id: 7, name: 'PHP + SQL', level: 4 },
  { id: 8, name: 'Docker + Github', level: 8 },
  { id: 9, name: 'UX/UI', level: 9 },
];

const portfolioItems = [
  {
    id: 'jbook',
    title: 'SPA "Multilingual Library «JBOOK»"',
    tags: ['Design', 'Layout', 'Angular', 'Express', 'MongoDB'],
    image: {
      desktop: '/img/jbook-ds-1x.jpg',
      tablet: '/img/jbook-tb-1x.jpg',
      alt: 'Multilingual Library «JBOOK»',
    },
    features: [
      'Progressive Web Application',
      'Angular Universal for search engines',
      'Using "Material Design" framework',
      'BackEnd with Express + MongoDB',
    ],
    links: {
      code: 'https://github.com/oleynichenko/book',
    },
    color: '#673bb7',
    colorLight: '#ded8e8',
  },
  {
    id: 'tests',
    title: 'Educational Quizzes "Pumping Tests"',
    tags: ['Design', 'Layout', 'Express', 'MongoDB'],
    image: {
      desktop: '/img/tests-ds-1x.jpg',
      tablet: '/img/tests-tb-1x.jpg',
      alt: 'Educational quizzes "Pumping Tests"',
    },
    features: [
      'Using "Material Design" framework',
      'BackEnd with Node.js + MongoDB',
      'Sharing quizz results in 3 social networks',
      "Admin panel for quizzes's authors",
    ],
    links: {
      code: 'https://github.com/oleynichenko/quiz-cms',
    },
    color: '#e4476c',
    colorDark: '#621527',
  },
  {
    id: 'words',
    title: 'SPA "English Words Trainer"',
    tags: ['Angular 7', 'NGRX', 'ANGULARFIRE2'],
    image: {
      desktop: '/img/words-ds-1x.jpg',
      tablet: '/img/words-tb-1x.jpg',
      alt: 'English Words Trainer',
    },
    features: [
      'User registration and authentication with Firebase',
      'Material Design components',
      'State management with NgRx',
      'Markup with angular/flex-layout',
    ],
    links: {
      code: 'https://github.com/oleynichenko/english-words-trainer',
      demo: 'http://english-words-trainer.s3-website.eu-central-1.amazonaws.com/',
    },
    color: '#303030',
    colorLight: '#F2F2F2',
  },
  {
    id: 'time',
    title: 'SPA "Time Tracker"',
    tags: ['Angular 7', 'Bootstrap 3'],
    image: {
      desktop: '/img/time-ds-1x.jpg',
      tablet: '/img/time-tb-1x.jpg',
      alt: 'Time Tracker',
    },
    features: [
      'Saving data in Local Storage',
      'Independence on page reloading',
      'Adding, deleting, pausing functions',
      'Edited task name',
    ],
    links: {
      code: 'https://github.com/oleynichenko/time-tracker',
      demo: 'http://time-tracker-we1r4s.s3-website-us-east-1.amazonaws.com',
    },
    color: '#527a51',
    colorLight: '#dff6de',
  },
  {
    id: 'recipe',
    title: 'Single Page Application "Recipe Book"',
    tags: ['Angular 7', 'NGRX', 'firebase', 'Bootstrap 3'],
    image: {
      desktop: '/img/recipe-ds-1x.jpg',
      tablet: '/img/recipe-tb-1x.jpg',
      alt: 'Recipe Book',
    },
    features: [
      'User registration and authentication with Firebase',
      'Lazy loading modules',
      'State management with NgRx',
      'Using Firebase SDK',
    ],
    links: {
      code: 'https://github.com/oleynichenko/recipe-book-ngrx',
      demo: 'http://recipe-book12345.s3-website.eu-central-1.amazonaws.com/',
    },
    color: '#e7e7e7',
    colorDark: '#2f2828',
  },
  {
    id: 'fitness',
    title: 'SPA "Fitness Tracker"',
    tags: ['Angular 7', 'NgRx', 'Angularfire2'],
    image: {
      desktop: '/img/fitness-ds-1x.jpg',
      tablet: '/img/fitness-tb-1x.jpg',
      alt: 'Fitness Tracker',
    },
    features: [
      'Registration and authentication',
      'Material Design components',
      'Markup with angular/flex-layout',
      'Database with angularfire2',
      'Firebase hosting',
    ],
    links: {
      code: 'https://github.com/oleynichenko/fitness-tracker-ngrx',
      demo: 'https://fitness-tracker-221a4.firebaseapp.com',
    },
    color: '#3f51b5',
    colorLight: '#e8eaf9',
  },
  {
    id: 'typing',
    title: 'Console Trainer “Typing Practice”',
    tags: ['Node', 'Yargs'],
    image: {
      desktop: '/img/typing-ds-1x.jpg',
      tablet: '/img/typing-tb-1x.jpg',
      alt: 'Console trainer “Typing Practice”',
    },
    features: [
      'Adding/deleting words for typing practice',
      'Selecting the number of words for the round',
      'Tracking progress in each round',
      'Saving results to a local file',
      'Effective motivation system',
    ],
    links: {
      code: 'https://github.com/oleynichenko/typing-practice',
    },
    color: '#8b9a62',
    colorDark: '#2a2b25',
  },
  {
    id: 'azbyka',
    title: 'Encyclopedia “Alphabet of Faith”',
    tags: ['Design'],
    image: {
      desktop: '/img/azb-ds-1x.jpg',
      tablet: '/img/azb-tb-1x.jpg',
      alt: 'Encyclopedia “Alphabet of Faith”',
    },
    features: [
      'Analog color scheme',
      'Canonical book proportions according Jan Tschichold',
      'Grid 8px',
      'Made with Adobe XD',
    ],
    links: {
      code: 'https://www.behance.net/gallery/70632601/Azbykaru-redesign',
    },
    color: '#6E4B0B',
    colorLight: '#FFF6E5',
  },
  {
    id: 'slider',
    title: 'Slider with SVG Gradient Background',
    tags: ['Javascript', 'SVG'],
    image: {
      desktop: '/img/slider-ds-1x.jpg',
      tablet: '/img/slider-tb-1x.jpg',
      alt: 'Slider with SVG background',
    },
    features: [
      'Changing to vertical state on small screens',
      'Moving gradient background',
      'Automatic moving to the nearest position',
      '"Drag and drop" feature',
    ],
    links: {
      code: 'https://codepen.io/oleynichenkos/pen/BMQVgg',
    },
    color: '#ebdcff',
    colorDark: '#35303c',
  },
  {
    id: 'device',
    title: 'Online Store “Device”',
    tags: ['layout', 'Design'],
    image: {
      desktop: '/img/device-ds-1x.jpg',
      tablet: '/img/device-tb-1x.jpg',
      alt: 'Online Store “Device”',
    },
    features: [
      'Design completion to 1200 px',
      'Sliders without JavaScript',
      'Centered responsive grid on "Catalog" page',
      'Pop-ups with static pages for disabled JavaScript',
      'Adaptive search form',
    ],
    links: {
      code: 'https://github.com/oleynichenko/device',
      demo: 'https://oleynichenko.github.io/device/index.html',
    },
    color: '#ffe27f',
    colorDark: '#665A32',
  },
  {
    id: 'pixel',
    title: 'Browser Game “Pixel-Hunter”',
    tags: ['javascript'],
    image: {
      desktop: '/img/pixel-ds-1x.jpg',
      tablet: '/img/pixel-tb-1x.jpg',
      alt: 'Browser Game “Pixel-Hunter”',
    },
    features: [
      'Single Page Application',
      'Saving last 10 game results',
      'MVP pattern',
      'Using ES-6',
    ],
    links: {
      code: 'https://github.com/oleynichenko/pixel-hunter',
      demo: 'https://oleynichenko.github.io/pixel-hunter/',
    },
    color: '#b3cfd0',
    colorDark: '#475252',
  },
  {
    id: 'brb',
    title: 'Website “Barbershop Borodinski”',
    tags: ['layout'],
    image: {
      desktop: '/img/brb-ds-1x.jpg',
      tablet: '/img/brb-tb-1x.jpg',
      alt: 'Website “Barbershop Borodinski”',
    },
    features: [
      'Adaptive images for Retina displays',
      '3 breakpoints',
      'Slider without JavaScript',
      'BEM-methodology',
      'Semantiс HTML markup',
    ],
    links: {
      code: 'https://github.com/oleynichenko/barbershop',
      demo: 'https://oleynichenko.github.io/barbershop/index.html',
    },
    color: '#000',
    colorLight: '#F2F2F2',
  },
  {
    id: 'pilates',
    title: 'Website “Personal Pilates Training”',
    tags: ['Design', 'layout', 'Php', 'javascript'],
    image: {
      desktop: '/img/pilates-ds-1x.jpg',
      tablet: '/img/pilates-tb-1x.jpg',
      alt: 'Website “Personal Pilates Training”',
    },
    features: [
      'Adaptive text blocks and images',
      'Animated images',
      'SVG icons',
      'Adaptive feedback form',
      'One color tone of the project',
    ],
    links: {
      code: 'https://github.com/oleynichenko/pilates',
      demo: 'https://pilates-trainer.github.io',
    },
    color: '#c7ade9',
    colorDark: '#40374B',
  },
  {
    id: 'todo',
    title: 'API: Organizer “ToDo App”',
    tags: ['Node', 'Express.js', 'mongoose', 'jsonwebtoken'],
    image: {
      desktop: '/img/todo-ds-1x.jpg',
      tablet: '/img/todo-tb-1x.jpg',
      alt: 'ToDo App',
    },
    features: [
      'User registration and authentication',
      'Authorization with JSON Web Tokens',
      'MongoDB from Mlab',
      'bcryptjs for confidential data',
      'Tests with mocha, supertest и expect',
    ],
    links: {
      code: 'https://github.com/oleynichenko/Todo-App',
    },
    color: '#695EB8',
    colorLight: '#E6E2FF',
  },
  {
    id: 'daat',
    title: 'API: Website “Daat Agency”',
    tags: ['React', 'Gatsby.js', 'CSS Animations'],
    image: {
      desktop: '/img/daat-ds-1x.jpg',
      tablet: '/img/daat-tb-1x.jpg',
      alt: 'ToDo App',
    },
    features: [
      'Animated titles',
      'Smooth appearance',
      'Gatsby.js framework',
      'Dark/light themes',
    ],
    links: {
      code: 'https://github.com/oleynichenko/daat',
      demo: 'https://daat.agency',
    },
    color: '#000',
    colorLight: '#F2F2F2',
  },
];

const WEBSITE_FEATURES = [
  'Cross-browser compatibility (IE11+)',
  'Responsive vs. Adaptive Design',
  'Semantic markup',
  'Correct work without CSS и JS',
  'Component Layout',
  'Image Optimization',
];

const TECHNOLOGIES = [
  'HTML5/Pug, CSS3/SASS',
  'Javascript, TypeScript',
  'NodeJS + Express + MongoDB',
  'Angular 7+, RxJs, NgRx',
  'React, Redux',
  'Material Design, Material-UI, PrimeNg frameworks',
];

const UPDATE_DATE = '2025-04-10';
const SECTION_HEIGHT = 400;

export {
  experienceItems,
  educationItems,
  SKILLS,
  UPDATE_DATE,
  SECTION_HEIGHT,
  TECHNOLOGIES,
  WEBSITE_FEATURES,
  portfolioItems,
};
